# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 193f5ac70856e998252820ec49b73a765f5f04bae38e061ebcc5b085b99c24025d072aff2486708352d3846c2711e65323fcb619b0d591e031ff97c48feeb0e7

test:
  secret_key_base: fe9b1e936b32d3a261fb262691bc8291a46cb08c51c780c3a869e070e65f3d05c6e7d6ce2d8f138efaac6c9ad087d75896433c14666e7066ca41811ff76de032

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
